x-dse-base: &dse-base
  image: datastax/dse-server:6.8.64
  platform: linux/amd64 # don't have arm images yet
  environment:
    DS_LICENSE: accept
services:
  core:
    <<: *dse-base
    ports:
    - "9042:9042" # CQL
    healthcheck:
      test: ["CMD", "sh", "-c", "cqlsh -e 'DESCRIBE KEYSPACES;' || exit 1"]
  graph: # Based on Gremlin
    <<: *dse-base
    command: ["-g"]
  spark:
    <<: *dse-base
    command: ["-k"]
  search: # Based on Solr 
    <<: *dse-base
    command: ["-s"]
  all: 
    <<: *dse-base
    command: ["-g", "-k", "-s"]